// ============================================================================
//  ĐẠO TẠNG — CHƯNG CẤT TINH TÚY (distilled canon essence)
//  Batch 1: 22 kinh then chốt, subagent-verified (DZ#/部/verbatim) + tự chưng cất.
//  ≥2 nguồn/entry. Normalize → shape LIBRARY. `node --check`.
// ============================================================================
import { ETHICS } from './amta-data.js';
export { ETHICS };

const DAOZANG_RAW = [
  // ── 太玄部 (triết lý) — agent distilled ─────────────────────────────────
  { dz: null, name_han: '道德经', name_vi: 'Đạo Đức Kinh', bu: '太玄', author: '老子 (李耳)', era: 'Xuân Thu', topic: 'philosophy',
    essence: '5000 chữ nền tảng toàn đạo giáo. «Đạo» = bản thể vô hình sinh thiên địa; «đức» = đạo ứng dụng. Vô vi nhi vô bất vi, «đạo pháp tự nhiên», nhu thắng cương.',
    key_text: '道可道，非常道；名可名，非常名。', use: 'tu tâm · 治 quốc · dưỡng sinh',
    sources: ['https://ctext.org/dao-de-jing/zhs (CTEXT)', 'https://zh.wikisource.org/zh-hans/%E9%81%93%E5%BE%B7%E7%B6%93 (維基文库)'],
    textual_certainty: 'high', notes: '老子/Xuân Thu; bản gốc không có 1 DZ# duy nhất.' },
  { dz: null, name_han: '南华真经（庄子）', name_vi: 'Nam Hoa Kinh (Trang Tử)', bu: '太玄', author: '庄周', era: 'Chiến Quốc', topic: 'philosophy',
    essence: '33 thiên. «Tề vật luận» (vạn vật bình đẳng), «tiêu dao du» (du tâm tự do tuyệt đối), «tâm trai/tọa vong». Cùng Lão → «lão trang» nền triết đạo.',
    key_text: '天地与我并生，而万物与我为一。', use: 'tu tâm · giải thoát tinh thần',
    sources: ['https://ctext.org/zhuangzi/zhs (CTEXT)', 'https://zh.wikisource.org/zh-hans/%E8%8E%8A%E5%AD%90 (維基文库)'],
    textual_certainty: 'high', notes: '庄周/Chiến Quốc chuẩn.' },
  { dz: null, name_han: '冲虚真经（列子）', name_vi: 'Liệt Tử', bu: '太玄', author: '列御寇', era: 'Chiến Quốc', topic: 'philosophy',
    essence: '8 thiên. Chủ «quý hư» («vạn vật sinh ư hư»). «Lực-mệnh», «ngụ ngôn» kinh điển (Sở nhân ưu thiên). «Tiên» phái.',
    key_text: '生者，理之必终者也。', use: 'tu tâm hư tịch · tiên học',
    sources: ['https://ctext.org/liezi/zhs (CTEXT)', 'https://zh.wikisource.org/zh-hans/%E5%88%97%E5%AD%90 (維基文库)'],
    textual_certainty: 'high', notes: '列御寇/Chiến Quốc.' },
  { dz: null, name_han: '通玄真经（文子）', name_vi: 'Văn Tử', bu: '太玄', author: '辛钘 (Tân Hình)', era: 'Chiến Quốc-Tây Hán', topic: 'philosophy',
    essence: 'Diễn Lão tử + hợp đạo-nho-pháp. 12 thiên. «Cửu thủ» (thủ hư/tĩnh/nhược), «vô vi nhi vô bất vi» vi chính trị thực dụng.',
    key_text: '老子曰：道者，所谓无状之状，无物之象也。', use: '治 quốc vô vi · binh pháp',
    sources: ['https://ctext.org/wiki.pl?if=gb&res=240539 (CTEXT)', 'https://zh.wikisource.org/zh-hans/%E6%96%87%E5%AD%90 (維基文库)'],
    textual_certainty: 'partial', notes: 'Tác giả/niên đại tranh cãi.' },
  { dz: null, name_han: '淮南子', name_vi: 'Hoài Nam Tử', bu: '太玄', author: '刘安 (Hoài Nam Vương)', era: 'Tây Hán', topic: 'philosophy',
    essence: '21 thiên — tập đại thành đạo gia Hán, dung hợp nho-pháp-âm dương. «Nguyên Đạo/Sơ Chân/Thiên Văn huấn». Chủ «vô vi nhi trị», thiên nhân cảm ứng.',
    key_text: '夫道者，覆天载地，廓四方，柝八极。', use: '治 quốc · thiên văn · thiên nhân hợp nhất',
    sources: ['https://ctext.org/huainanzi/zhs (CTEXT)', 'https://zh.wikisource.org/zh-hans/%E6%B7%AE%E5%8D%97%E5%AD%90 (維基文库)'],
    textual_certainty: 'high', notes: 'Lưu An/Tây Hán; bản gốc KHÔNG thuộc chính thống 道藏.' },

  // ── 洞玄部 (linh bảo / 科仪) — agent distilled ───────────────────────────
  { dz: 'DZ0001', name_han: '度人经（元始无量度人上品妙经）', name_vi: 'Độ Nhân Kinh', bu: '洞玄', author: '古灵宝经', era: 'Đông Tấn末-Nam Triều', topic: 'classic',
    essence: '«Đạo tạng thủ kinh» (DZ0001, mở đầu đạo tạng). Nguyên Thủy Thiên Tôn phổ độ chi pháp, dùng «phạm khí chân văn» khai độ u minh. «Tiên đạo quý sinh, vô lượng độ nhân».',
    key_text: '仙道贵生，无量度人', use: '度亡 · 诵经 · 灵宝斋醮',
    sources: ['https://zh.wikisource.org/zh-hans/%E9%9D%88%E5%AF%B6%E7%84%A1%E9%87%8F%E5%BA%A6%E4%BA%BA%E4%B8%8A%E5%93%81%E5%A6%99%E7%B6%93/1 (維基文库)', 'https://zh.daoinfo.org/index.php?title=%E5%A4%AA%E4%B8%8A%E6%B4%9E%E7%8E%84%E9%9D%88%E5%AF%B6%E5%85%83%E5%A7%8B%E7%84%A1%E9%87%8F%E5%BA%A6%E4%BA%BA%E4%B8%8A%E5%93%81%E5%A6%99%E7%B6%93 (daoinfo)'],
    textual_certainty: 'high', notes: 'DZ0001 đạo tạng thủ kinh.' },
  { dz: 'DZ0318', name_han: '九天生神章经', name_vi: 'Cửu Thiên Sinh Thần Chương Kinh', bu: '洞玄', author: '古灵宝经', era: 'Đông Tấn', topic: 'cultivation',
    essence: 'Tam nguyên hóa cửu khí → cửu thiên, mỗi thiên 1 «sinh thần chương» an trấn hồn phách. «Cửu quá vi nhất biến» → vong giả trừ tử thăng chân nhân.',
    key_text: '九过为一遍，一遍周竟，三界举名，五帝友敬，称为真人。', use: '度亡 · an trấn hồn phách · sinh thần',
    sources: ['https://zh.wikisource.org/zh-hans/%E6%B4%9E%E7%8E%84%E9%9D%88%E5%AF%B6%E8%87%AA%E7%84%B6%E4%B9%9D%E5%A4%A9%E7%94%9F%E7%A5%9E%E7%AB%A0%E7%B6%93 (維基文库)', 'https://www.shidianguji.com/book/DZ0318 (識典古籍 DZ0318)'],
    textual_certainty: 'high', notes: 'DZ0318 洞玄部本文類.' },
  { dz: 'DZ1439', name_han: '洞玄灵宝玉京山步虚经', name_vi: 'Ngọc Kinh Sơn Bộ Hư Kinh', bu: '洞玄', author: '古灵宝经', era: 'Đông Tấn末-Nam Triều初', topic: 'ritual',
    essence: 'Ngọc Kinh Sơn = trung tâm thế giới bộ hư nghi. Định «bộ hư» khoa thức (tụng + tuyên hành «tượng phi thăng»). Nền mọi «bộ hư từ» +斋醮 tiết tấu.',
    key_text: '修灵宝洞玄斋，诵空洞步虚章，先叩齿三通，咽漱三过。', use: '步虚仪 · 灵宝斋醮',
    sources: ['https://zh.wikisource.org/zh-hans/%E6%B4%9E%E7%8E%84%E9%9D%88%E5%AF%B6%E7%8E%89%E4%BA%AC%E5%B1%B1%E6%AD%A5%E8%99%9B%E7%B6%93 (維基文库)', 'https://www.shidianguji.com/book/DZ1439 (識典古籍 DZ1439)'],
    textual_certainty: 'high', notes: 'DZ1439 (Vạn Lịch tục đạo tạng).' },
  { dz: null, name_han: '灵宝无量度人上经大法', name_vi: 'Linh Bảo Vô Lượng Độ Nhân Đại Pháp', bu: '洞真', author: ' (đề «thiên chân hoàng nhân»; thực Tống-Nguyên-Minh biên)', era: 'Tống-Nguyên', topic: 'ritual',
    essence: '72卷 linh bảo đạo pháp TỔNG TẬP — chú疏 + 符籙 nghi + đàn trượng hành trì. «Bách khoa» khoa nghi linh bảo. ⚠ KHÔNG phải cổ linh bảo kinh, là Tống-Nguyên-Minh biên tập.',
    key_text: null, use: '科仪 tổng tập · 符籙斋醮',
    sources: ['https://zh.wikisource.org/zh-hans/%E9%9D%88%E5%AF%B6%E7%84%A1%E9%87%8F%E5%BA%A6%E4%BA%BA%E4%B8%8A%E7%B6%93%E5%A4%A7%E6%B3%95 (維基文库)', 'https://zh.daoinfo.org/index.php?title=%E7%81%B5%E5%AF%B6%E7%84%A1%E9%87%8F%E5%BA%A6%E4%BA%BA%E4%B8%8A%E7%B6%93%E5%A4%A7%E6%B3%95 (daoinfo)'],
    textual_certainty: 'partial', notes: '⚠ KHÔNG phải cổ linh bảo kinh; 道藏 = 洞真部·方法類 (KHÔNG phải 洞玄).' },

  // ── 洞真/洞玄 (thượng thanh) — agent distilled ──────────────────────────
  { dz: 'DZ1016', name_han: '真诰', name_vi: 'Chân Cáo', bu: '太玄', author: '陶弘景', era: 'Lương (~499)', topic: 'classic',
    essence: 'Bộ thư nền tảng thượng thanh — ghi «chân nhân giáng cơ» cho Dương Hi + họ Hứa (Đông Tấn); Ngụy Hoa Tồn trao truyền thượng thanh. Ghi «Bắc Đế sát quỷ đại pháp» (天蓬 chú nguồn).',
    key_text: '伏寻上清真经出世之源，始于晋哀帝兴宁二年…紫虚元君上真司命南岳魏夫人下降，授弟子…杨某，使作隶字写出。', use: 'thư tịch gốc thượng thanh · 存思/giới 诫',
    sources: ['https://zh.wikisource.org/wiki/%E7%9C%9F%E8%AA%A5 (維基文库)', 'https://ctext.org/wiki.pl?if=gb&res=80529 (CTEXT)'],
    textual_certainty: 'high', notes: '陶弘景/Lương.' },
  { dz: 'DZ421', name_han: '登真隐诀', name_vi: 'Đăng Chân Ẩn Quyết', bu: '洞玄', author: '陶弘景', era: 'Lương', topic: 'cultivation',
    essence: 'Tổng tập mật quyết «đăng chân» thượng thanh — 佩符 + 存思 cửu cung chân thần + thủ nhất + phục khí + đạo dẫn. Nguyên 24-25 quyển, NAY CHỈ CÒN 3 quyển (tàn). Bổ sung «Chân Cáo».',
    key_text: '知白守黑，欲死不得，知黑守白，万邪消却。', use: 'tu hành mật quyết · thượng thanh cultivation manual',
    sources: ['https://zh.wikisource.org/zh-hans/%E7%99%BB%E7%9C%9F%E9%9A%B1%E8%A8%A3 (維基文库 全文)', 'https://www.kanripo.org/text/KR5b0105/ (Kanripo KR5b0105)'],
    textual_certainty: 'partial', notes: 'DZ421; ⚠ 洞玄部·玉诀類 (không phải 洞真); tàn 3卷.' },
  { dz: 'DZ331', name_han: '黄庭内景经', name_vi: 'Hoàng Đình Nội Cảnh Kinh', bu: '洞玄', author: '魏华存 (truyền) / 上清派', era: 'Đông Tấn', topic: 'cultivation',
    essence: 'Kinh cốt tủy thượng thanh do Ngụy Hoa Tồn truyền — thể thất ngôn 36 chương. Pháp «tồn tư» thân thần: ngũ tạng lục phủ đều có thần (tâm thần Đan Nguyên thủ Linh...), tâm thần chủ cung «Hoàng Đình». Tồn thần + phục khí + trừ tam thi → trường sinh.',
    key_text: '六腑五脏神体精，皆在心内运天经，昼夜存之自长生', use: '存思 · 存神养神 · 服气咽津 · 去三尸',
    sources: ['https://zh.wikisource.org/zh-hans/%E9%BB%83%E5%BA%AD%E5%85%A7%E6%99%AF%E7%B6%93 (維基文库)', 'https://www.kanripo.org/text/KR5b0015/ (Kanripo KR5b0015)'],
    textual_certainty: 'high', notes: 'DZ331 洞玄部本文類 (verified); 魏华存/上清.' },
  { dz: null, name_han: '上清大洞真经', name_vi: 'Thượng Thanh Đại Đồng Chân Kinh', bu: '洞真', author: '三茅/杨羲 truyền → 陶弘景', era: 'Đông Tấn-Lương', topic: 'cultivation',
    essence: '«Thượng thanh nhất đại kinh» — 39 chương, mỗi chương = 1 thần chân nhân ứng 1 môn huyệt. 存思 thần + «hồi phong hỗn hợp» — tu pháp cao nhất thượng thanh.',
    key_text: null, use: '存思 · tu chân',
    sources: ['https://ctext.org/wiki.pl?if=gb&res=71843 (CTEXT)', 'https://zh.wikipedia.org/wiki/%E4%B8%8A%E6%B8%85%E5%A4%A7%E6%B4%9E%E7%9C%9F%E7%BB%8F (維基百科)'],
    textual_certainty: 'partial', notes: '39 chương/thần-môn hệ chuẩn.' },

  // ── 科仪 / 劝善 / nội đan — agent distilled ──────────────────────────────
  { dz: 'DZ1167', name_han: '太上感应篇', name_vi: 'Thái Thượng Cảm Ứng Thiên', bu: '太清', author: ' (khuyết danh; 南宋 李昌龄 truyền chú — KHÔNG phải «李昌世»)', era: 'Bắc Tống末-Nam Tống', topic: 'classic',
    essence: 'Kinh khuyên thiện nền tảng đạo giáo: thiên địa có thần (司过之神/tam thi/táo thần) giám sát ghi tội phạt, «hoạ phúc vô môn, duy nhân tự triệu», «thiện ác chi báo, như ảnh tùy hình». Tích thiện trừ ác, cốt lõi tịnh âm tà/cải mệnh.',
    key_text: '太上曰：祸福无门，惟人自召；善恶之报，如影随形。', use: '劝善 · 改过 · cải mệnh',
    sources: ['https://zh.wikisource.org/zh-hans/%E5%A4%AA%E4%B8%8A%E6%84%9F%E5%BA%94%E7%AF%87 (維基文库)', 'https://www.shidianguji.com/book/DZ1167 (識典古籍 DZ1167)'],
    textual_certainty: 'high', notes: 'DZ1167 太清部(辅洞神); 南宋 李昌龄 truyền chú.' },
  { dz: null, name_han: '文昌帝君阴骘文', name_vi: 'Văn Xương Đế Quân Âm Chỉ Văn', bu: '道藏辑要', author: ' (khuyết danh, 托文昌; 宋-Nguyên phù bút)', era: '宋-Nguyên', topic: 'classic',
    essence: 'Khuyên «quảng hành âm chất» (tích âm đức ngầm, hành thiện không ai biết): cứu nạn/tế cấp/mẫn cô/ấn kinh/giới sát. «Âm chất = trời ngầm bảo độ người thiện»; trọng «tâm địa».',
    key_text: '欲广福田，须凭心地。', use: '劝善 · tích âm đức · văn vận',
    sources: ['https://zh.wikisource.org/zh-hans/%E6%96%87%E6%98%8C%E5%B8%9D%E5%90%9B%E9%98%B4%E9%99%9F%E6%96%87 (維基文库)', 'https://zh.daoinfo.org/index.php?title=%E6%96%87%E6%98%8C%E5%B8%9D%E5%90%9B%E9%99%B0%E9%A8%AD%E6%96%87 (daoinfo)'],
    textual_certainty: 'high', notes: '⚠ KHÔNG thuộc 正统道藏; chỉ 清《道藏辑要》/《藏外道书》 thu.' },
  { dz: 'DZ645', name_han: '太上老君内日用妙经', name_vi: 'Thái Thượng Lão Quân Nội Nhật Dụng Diệu Kinh', bu: '洞神', author: ' (khuyết danh, 托太上老君)', era: '约 Tống', topic: 'cultivation',
    essence: 'Nội nhật dụng — tĩnh tọa nội đan: «ẩm thực tắc định, cấm khẩu độc tọa, mạc khởi nhất niệm», điều tức miên miên, tâm hỏa tự giáng, thận thủy tự thăng, «thập nhị thời thường yếu thanh tĩnh». ⚠ «太上玄門日用妙 kinh» KHÔNG tồn tại — thực là «太上老君 nội/ngoại nhật dụng diệu kinh» DZ645.',
    key_text: '夫日用者，饮食则定，禁口独坐，莫起一念。万事俱忘，存神定意。', use: '修真 · nội đan tĩnh tọa · nhật dụng hành trì',
    sources: ['https://zh.wikisource.org/zh-hans/%E5%A4%AA%E4%B8%8A%E8%80%81%E5%90%9B%E5%85%A7%E6%97%A5%E7%94%A8%E5%A6%99%E7%B6%93 (維基文库)', 'https://www.kanripo.org/text/KR5c0026/ (Kanripo KR5c0026)'],
    textual_certainty: 'partial', notes: 'DZ645 洞神部本文類 (傷字号, thất kinh đồng quyển).' },
  { dz: 'DZ1138', name_han: '无上秘要', name_vi: 'Vô Thượng Bí Yếu', bu: '太平', author: '北周武帝/通道观学士 (王延 tham biên)', era: 'Bắc Chu (~574–578)', topic: 'classic',
    essence: 'Loại thư (bách khoa) Đạo giáo xưa nhất — nguyên 100卷/292 phẩm (nay tàn 67-68卷). Hệ thống hóa vũ trụ quan/giới uy nghi/tu chân,调和 giáo phái. Cẩm nang tra cứu giáo nghĩa thời Lục triều, trước 云笈七签.',
    key_text: null, use: 'bách khoa · tham chiếu giáo nghĩa',
    sources: ['https://zh.wikisource.org/zh-hans/%E7%84%A1%E4%B8%8A%E7%A7%98%E8%A6%81 (維基文库)', 'https://www.shidianguji.com/book/DZ1138 (識典古籍 DZ1138)', 'https://github.com/kanripo/KR5e0040 (Kanripo KR5e0040)'],
    textual_certainty: 'high', notes: 'DZ1138 太平部; 北周武帝/通道观学士 (王延 tham biên, phi độc soạn).' },
  { dz: 'DZ13', name_han: '高上玉皇心印妙经（心印经）', name_vi: 'Tâm Ấn Kinh', bu: '洞真', author: ' (khuyết danh)', era: 'Đường末-Ngũ Đại-Bắc Tống', topic: 'cultivation',
    essence: 'Tâm pháp nội đan cốt tủy — tinh-khí-thần = «thượng dược tam phẩm», «thần hợp khí, khí hợp chân». 50 câu/200 chữ, «tồn vô thủ hữu/hồi phong hỗn hợp». Công khóa tất tụng hằng ngày (cùng常清静经).',
    key_text: '上药三品，神与气精。恍恍惚惚，杳杳冥冥。', use: 'nội đan · 日诵功课',
    sources: ['https://zh.wikisource.org/wiki/%E9%AB%98%E4%B8%8A%E7%8E%89%E7%9A%87%E5%BF%83%E5%8D%B0%E7%B6%93 (維基文库)', 'https://zh.daoinfo.org/index.php?title=%E9%AB%98%E4%B8%8A%E7%8E%89%E7%9A%87%E5%BF%83%E5%8D%B0%E7%B6%93 (daoinfo)'],
    textual_certainty: 'high', notes: 'DZ13 洞真部本文類; 玉皇 hệ.' },

  // ── 太清 / 正一 / 太平 — agent distilled (Schipper-Verellen + Pregadio verified) ──
  { dz: 'DZ332', name_han: '黄庭外景经', name_vi: 'Hoàng Đình Ngoại Cảnh Kinh', bu: '太清', author: ' (khuyết danh; truyền Lão Quân/魏华存)', era: 'Đông Tấn (~4c, sớm hơn nội cảnh DZ331)', topic: 'cultivation',
    essence: 'Kinh dưỡng sinh tối cổ — thể thất ngôn, nền nội đan sau. Lấy Hoàng Đình-Đan Điền làm gốc, phối ân tân (nuốt «ngọc thanh») + thủ tinh + hô hấp; «tử dục bất tử tu Côn Lôn» (đỉnh đầu/thượng đan điền). Đơn giản + sớm hơn nội cảnh; Vương Hi Chi thư pháp truyền sao.',
    key_text: '上有黄庭下关元，后有幽阙前命门……子欲不死修昆仑。', use: 'dưỡng sinh · tồn tư · nội đan sơ kỳ',
    sources: ['https://zh.wikisource.org/zh-hans/黄庭外景经 (維基文库)', 'https://ctext.org/wiki.pl?if=gb&chapter=560368 (CTEXT DZ332)'],
    textual_certainty: 'high', notes: 'DZ332 (Schipper-Verellen/Brill); sớm hơn nội cảnh DZ331.' },
  { dz: 'DZ880', name_han: '太清金液神丹经', name_vi: 'Thái Thanh Kim Dịch Thần Đan Kinh', bu: '太清', author: ' (khuyết danh; truyền 葛玄, 葛洪 bảo tồn)', era: 'Đông Tấn-Lục Triều', topic: 'cultivation',
    essence: 'Kinh quan trọng nhất hệ «Thái Thanh đạo» NGOẠI ĐAN (Pregadio: Great Clarity). Bản đạo tạng hợp nhất tam kinh (Thái Thanh/ Cửu Đan/ Kim Dịch). Dược pháp luyện đan khoáng (chu sa-kim-lưu huỳnh-thủy ngân) thành «Kim Dịch-Cửu Đan» — «ngoại luyện chi cực».',
    key_text: '金液丹華是天經，泰清神仙諒分明。當立精誠乃可營，玩之不休必長生。', use: 'ngoại đan · luyện đan khoáng',
    sources: ['https://ctext.org/wiki.pl?if=gb&res=559064 (CTEXT DZ880)', 'https://baike.baidu.com/item/%E5%A4%AA%E6%B8%85%E9%87%91%E6%B6%B2%E7%A5%9E%E4%B8%B9%E7%BB%8F (百度百科)'],
    textual_certainty: 'high', notes: 'DZ880 (Pregadio Great Clarity); tam kinh hợp nhất.' },
  { dz: 'DZ821', name_han: '太上老君养生诀', name_vi: 'Thái Thượng Lão Quân Dưỡng Sinh Quyết', bu: '太清', author: ' (khuyết danh, ngụy; đề «Hoa Đà truyền Ngô Phổ»)', era: 'Lục Triều-Đường', topic: 'cultivation',
    essence: '3 thiên: (1) Ngũ cầm hí (hổ-hùng-lộc-viên-ô); (2) LỤC TỰ khẩu quyết Sát-Ha-Hô-Hư-Xuy-Hi (phổi-tim-lách-gan-thận-tam tiêu); (3) Dưỡng sinh chân quyết. «Trừ lục hại, thập lục thiểu»; «thân như quốc: thần do quân, huyết do thần, khí do dân». Văn bản nguồn của «lục tự quyết» khí công.',
    key_text: '一人之身，一国之象也……神犹君也，血犹臣也，气犹民也。', use: 'dưỡng sinh · đạo y · lục tự quyết · ngũ cầm hí',
    sources: ['https://zh.wikisource.org/zh-hans/太上老君养生诀 (維基文库)', 'https://ctext.org/wiki.pl?if=gb&chapter=913232 (CTEXT DZ821)'],
    textual_certainty: 'high', notes: 'DZ821 (Schipper-Verellen Vol.3 / Jia Jinhua 2015).' },
  { dz: 'DZ818', name_han: '太清导引养生经', name_vi: 'Thái Thanh Đạo Dẫn Dưỡng Sinh Kinh', bu: '太清', author: ' (khuyết danh)', era: 'Lục Triều-Đường (~4c)', topic: 'cultivation',
    essence: 'Kinh tối trọng về ĐẠO DẪN (khởi công thể dục trị liệu). Ghi phép đạo dẫn của Xích Tùng Tử/Ninh tiên sinh/Vương Kiều/Bành Tổ + «bắt chước loài vật» (hạp miêu/quy/long hành khí). «Hấp nhật tinh ba thời» (nhật xuất/trung/nhập), trị bệnh cụ thể. Liên quan Mã Vương Đôi đạo dẫn.',
    key_text: '日初出、日中、日入，此三时向日正立，不息九通，仰头吸日精光，九咽之，益精百倍。', use: 'đạo y · dưỡng sinh · đạo dẫn · hành khí',
    sources: ['https://zh.wikisource.org/zh-hans/太清导引养生经 (維基文库)', 'https://ctext.org/wiki.pl?if=gb&res=297375 (CTEXT DZ818)'],
    textual_certainty: 'high', notes: 'DZ818 (Verellen 2004 / Despeux 2018 / Kohn 2008); trùng «Cổ Tiên Đạo Dẫn Án Ma Pháp».' },
  { dz: 'DZ1208', name_han: '太上三五正一盟威箓', name_vi: 'Chính Nhất Minh Uy Lục', bu: '正一', author: ' (khuyết danh; truyền thống Trương Đạo Lăng/Thiên Sư đạo)', era: 'Hán mạt-Ngụy Tấn (truyền 142 CN)', topic: 'fu',
    essence: 'Kinh lục TỔ của chính nhất đạo — 6 quyển ghi 24 giai pháp lục (Đồng Tử → Diên Sinh Bảo Mệnh). Truyền Lão Quân giáng thụ Trương Đạo Lăng tại Hạc Minh Sơn (142 CN); mỗi lục kèm thần tướng/khí để đạo sĩ役使. Định lập cấp bậc «Phong Lục/授箓» cốt yếu thiên sư đạo, nền chế độ授箓 đời sau.',
    key_text: '上屬北斗某星君，言被五炁神童君召', use: '符籙 · 24 giai Phong Lục · 役使 thần tướng · bảo mệnh trừ tà',
    sources: ['https://www.shidianguji.com/book/DZ1208 (識典古籍 DZ1208)', 'https://zh.daoinfo.org/index.php?title=太上三五正一盟威箓 (daoinfo)'],
    textual_certainty: 'high', notes: 'DZ1208 正一部; truyền 142 CN Hạc Minh Sơn.' },
  { dz: 'DZ0789', name_han: '正一法文天师教戒科经', name_vi: 'Chính Nhất Pháp Văn Giáo Giới Khoa Kinh', bu: '正一', author: ' (khuyết danh; khả năng hậu duệ Trương Lỗ)', era: 'Tào Ngụy-Lục Triều (3-5c)', topic: 'ritual',
    essence: '5 thiên giáo giới hợp nhất quyển — mượn khung Lão Quân truyền giới cho Trương Đạo Lăng để quy phạm đạo dân: tấn kính thờ sư, hiếu dưỡng song thân, cứu bần cấp nạn, cấm dâm-bạo-ninh-độc. Nền giới luật + khoa nghi thiên sư đạo sơ kỳ, ảnh hưởng cải cách Khấu Khiêm Chi.',
    key_text: '奉道不可不勤，事师不可不敬，事亲不可不孝', use: '教戒/戒律 · quy phạm đạo dân · 24 trị khoa nghi',
    sources: ['https://www.shidianguji.com/zh/book/DZ0789 (識典古籍 DZ0789)', 'https://zh.daoinfo.org/index.php?title=正一法文天师教戒科经 (daoinfo)'],
    textual_certainty: 'high', notes: 'DZ0789 (chính thống đạo藏 洞神部·giới luật loại; hệ Chính Nhất Pháp Văn).' },
  { dz: 'DZ1101', name_han: '太平经', name_vi: 'Thái Bình Kinh', bu: '太平', author: ' (truyền 于吉 thụ thần nhân; 宫崇 hiến thư)', era: 'Đông Hán mạt (2c)', topic: 'classic',
    essence: 'Kinh điển LỚN NHẤT sơ kỳ đạo giáo — nguyên 170 quyển 10 bộ (giáp-quý), hiện tồn 57. «Nguyên khí» sinh thiên-địa-nhân; «thượng hoàng thái bình khí» sắp đến; công bằng xã hội (三合相通, chống tích lũy bóc lột). Tư tưởng gốc Thái Bình Đạo (Trương Giác) + ảnh hưởng Thiên Sư đạo; dưỡng sinh thủ nhất + trị quốc trị thân song tu.',
    key_text: '天地开辟贵本根，乃气之元也。欲致太平，念本根也', use: 'trị quốc thái bình · dưỡng sinh thủ nhất · âm dương ngũ hành',
    sources: ['https://ctext.org/wiki.pl?if=gb&chapter=84713 (CTEXT DZ1101 合校)', 'https://zh.wikipedia.org/zh-cn/太平经 (維基百科)', 'https://en.daoinfo.org/wiki/The_Book_of_Supreme_Peace (daoinfo EN)'],
    textual_certainty: 'high', notes: 'DZ1101 太平部; nguyên 170卷 hiện 57.' },
  { dz: 'DZ1101b', name_han: '太平经钞', name_vi: 'Thái Bình Kinh Sao', bu: '太平', author: '闾丘方远 (Lữ Khưu Phương Viễn, Đường mạt)', era: 'Đường mạt (9-10c)', topic: 'classic',
    essence: 'Tiết lục 10 quyển do Lữ Khưu Phương Viễn soạn, theo thiên can (giáp-quý) ứng 10 bộ nguyên Thái Bình Kinh (đã tản thất). Văn bản quan trọng nhất PHỤC CỔ — Vương Minh «Thái Bình Kinh Hợp Hiệu» dựa vào nó + 27 dẫn thư khôi phục ~170 quyển.',
    key_text: '天下凡事，皆一阴一阳，乃能相生，乃能相养', use: '节钞 · phục cổ Thái Bình Kinh',
    sources: ['https://zh.wikisource.org/zh-hans/太平經鈔 (維基文库)', 'https://www.shidianguji.com/book/DZ1101b (識典古籍 DZ1101b)'],
    textual_certainty: 'partial', notes: 'DZ1101b; Lữ Khưu Phương Viễn/Đường mạt; giáp bộ nghi hậu nhân bổ sung.' },
];

export const DAOZANG = DAOZANG_RAW.map((e) => ({
  id: 'DZ_' + (e.dz ? String(e.dz).replace(/\D/g, '') : (e.name_han || '').replace(/[^一-龥]/g, '').slice(0, 6)),
  layer: 'daozang',
  name_han: e.name_han,
  name_vi: e.name_vi || '',
  school: `${e.bu || '道藏'} bộ` + (e.author ? ` · ${e.author}` : '') + (e.era ? ` · ${e.era}` : ''),
  han_text: e.key_text || '',
  meaning: e.essence || '',
  use: e.use || '',
  sources: Array.isArray(e.sources) ? e.sources.filter(Boolean) : [],
  textual_certainty: e.textual_certainty || 'partial',
  bu: e.bu || '',
  author: e.author || '',
  era: e.era || '',
  topic: e.topic || '',
  notes: (e.dz ? `道藏 ${e.dz}` : '道藏 kinh') + (e.notes ? ' · ' + e.notes : ''),
})).filter((e) => e.name_han && e.sources.length >= 2);

export function daozangByBu(entries = DAOZANG) {
  const c = {};
  for (const e of entries) c[e.bu] = (c[e.bu] || 0) + 1;
  return c;
}
