// ============================================================================
//  KINH DỊCH 64 QUẺ — Ý NGHĨA TIẾNG VIỆT (Dịch cho AI + user hiểu)
//  Nguồn luận giải: 《周易》彖傳/大象傳 (public domain). Key = tên GIẢN THỂ
//  (khớp heluo.js HEX64 + meihua.js). Mỗi quẻ: num, nameVi, nature, fortune (VN),
//  image (hình ảnh ẩn dụ, diễn giải VN — KHÔNG trích Hán để tránh garble), tone.
//
//  [loop 545] FEATURE: kết hợp các loại quẻ Dịch khắp app. Module này là nguồn
//  nghĩa VN chung cho 河洛理数 + 鬼谷分定經 + 梅花易数 (3 hệ đều quy về 64 quẻ).
// ============================================================================
const HEX_MEANING = {
  '乾': { num: 1, nameVi: 'Càn', nature: 'cương kiện, sáng tạo',
    fortune: 'Trời trên trời — sức sáng tạo vô song, tự cường không ngừng. Đỉnh cao vận thế, nên tiến nhưng phải khiêm nhường; kiêu ngạo thì thịnh cực sinh hối.',
    image: 'Trời vận hành không ngừng — bậc quân tử tự cường不息.', tone: 'cát' },
  '坤': { num: 2, nameVi: 'Khôn', nature: 'nhu thuận, bao dung',
    fortune: 'Đất trên đất — ôn hoà bao dung, thuận tùng nuôi dưỡng. Nên đi theo đừng dẫn đầu, giữ tĩnh thì hanh thông; tranh đấu thì hung.',
    image: 'Đất dày chở vạn vật — quân tử dùng đức hậu tải vật.', tone: 'cát' },
  '屯': { num: 3, nameVi: 'Truân', nature: 'khó khăn khởi đầu',
    fortune: 'Mây sấm hội mà chưa mưa — khởi đầu gian nan, rối ren. Chớ nôn nóng, tìm người giúp đỡ, kiên nhẫn lập nền thì sau hanh.',
    image: 'Mây sấm tụ — quân tử lo liệu xây dựng cơ nghiệp.', tone: 'trung' },
  '蒙': { num: 4, nameVi: 'Mông', nature: 'mông muội, cần học',
    fortune: 'Nước dưới núi — như trẻ chưa khai minh. Cầu học, tìm thầy; giáo dục nhất quán thì giải được mông muội.',
    image: 'Núi sinh suối — quân tử hành động quả quyết nuôi đức.', tone: 'trung' },
  '需': { num: 5, nameVi: 'Nhu', nature: 'chờ đợi đúng thời',
    fortune: 'Mây tụ chưa mưa — cần chờ thời. Nuôi dưỡng thực lực, đừng vội tiến; chờ đúng thời thì lợi lớn.',
    image: 'Mây lên trời — quân tử ẩm thực yến lạc nuôi sức chờ thời.', tone: 'cát' },
  '讼': { num: 6, nameVi: 'Tụng', nature: 'tranh chấp, kiện cáo',
    fortune: 'Trời trên nước — trời nước đi ngược nhau, tâm bất đồng. Tranh tụng dễ gây hoạ; tránh kiện, tìm trung gian, biết lùi thì «trung cát».',
    image: 'Trời nước đi ngược — quân tử làm việc lo tính từ đầu.', tone: 'hung' },
  '师': { num: 7, nameVi: 'Sư', nature: 'dẫn dắt, kỷ luật',
    fortune: 'Nước ngầm trong đất — đông đảo ẩn tàng. Như tướng lĩnh quân, cần kỷ luật, công bằng, trách nhiệm; dùng đúng người thì cát.',
    image: 'Đất chứa nước — quân tử dung dân, nuôi dưỡng chúng.', tone: 'trung' },
  '比': { num: 8, nameVi: 'Tỷ', nature: 'gắn bó, quy phụ',
    fortune: 'Nước thấm đất — thân cận, phụ giúp. Chọn đúng người để theo, gắn bó chân thành; nhưng phụ thuộc quá mức thì mất tự chủ.',
    image: 'Trên dưới đất hoà hợp — vua kiến lập chư hầu thân cận.', tone: 'cát' },
  '小畜': { num: 9, nameVi: 'Tiểu Súc', nature: 'tích lũy nhỏ',
    fortune: 'Gió trên trời — mây kín chưa mưa, lực mềm kìm cứng. Tích lũy từng bước, kiên nhẫn; thuở nhỏ vất vả, trung niên phát.',
    image: 'Gió trôi trên trời — quân tử rèn luyện văn đức.', tone: 'trung' },
  '履': { num: 10, nameVi: 'Lý', nature: 'cẩn trọng bước đi',
    fortune: 'Trời trên đầm — dậm đuôi hổ mà không bị cắn. Hành động cẩn thận giữa cảnh nguy, giữ lễ phân tôn ti thì an.',
    image: 'Trời trên đầm — quân tử phân định trên dưới, an dân chí.', tone: 'trung' },
  '泰': { num: 11, nameVi: 'Thái', nature: 'hanh thông, giao hoà',
    fortune: 'Đất trên trời — thiên địa giao thái, vạn sự hanh thông. Âm dương hoà hợp, thời vận tốt; tận dụng nhưng phòng «thành phúc ư hoàng».',
    image: 'Trời đất giao hoà — người quân tử tài bồi đạo trời đất.', tone: 'cát' },
  '否': { num: 12, nameVi: 'Bĩ', nature: 'bế tắc',
    fortune: 'Trời trên đất — thiên địa không giao, bế tắc. Tiểu nhân đắc thế; giữ mình ẩn náu, đừng hành động lớn, đợi thời mở ra.',
    image: 'Trời đất không giao — quân tử kiệm đức tránh nạn.', tone: 'hung' },
  '同人': { num: 13, nameVi: 'Đồng Nhân', nature: 'hợp tác đồng lòng',
    fortune: 'Trời trên lửa — lửa bốc lên trời cùng hướng. Hợp tác chân thành, bao dung; dùng đạo lý công khai thu phục lòng người, tránh phe phái.',
    image: 'Trời lửa cùng hướng — quân tử phân loại biệt vật để hợp tác.', tone: 'cát' },
  '大有': { num: 14, nameVi: 'Đại Hữu', nature: 'sở hữu lớn',
    fortune: 'Lửa trên trời — mặt trời giữa trời, phú quý. Sở hữu lớn, thành tựu lớn; cần đức khiêm, thịnh cực tất suy nên cẩn.',
    image: 'Lửa trên trời — quân tử遏 ác dương thiện (ngăn ác, làm lành).', tone: 'cát' },
  '谦': { num: 15, nameVi: 'Khiêm', nature: 'khiêm nhường',
    fortune: 'Đất trên núi — núi cao mà tự ở dưới đất, khiêm. Đức khiêm thì tai qua nạn khỏi; có tài không khoe. Quẻ duy nhất 64 đều cát.',
    image: 'Đất chứa núi — quân tử giảm dư bù thiếu, giữ cân bằng.', tone: 'cát' },
  '豫': { num: 16, nameVi: 'Dự', nature: 'vui vẻ, chuẩn bị',
    fortune: 'Sấm trên đất — sấm vang đất rung, vui. Lạc quan, yêu nghệ thuật; nhưng «khoái lạc» dễ sa buông tuồng, cần nghiêm túc chuẩn bị trước.',
    image: 'Sấm động đất rền — vua làm nhạc tôn đức, cúng Thượng Đế.', tone: 'cát' },
  '随': { num: 17, nameVi: 'Tùy', nature: 'thuận tùng, linh hoạt',
    fortune: 'Đầm trên sấm — sấm trong đầm nghỉ, thuận theo. Theo đúng thời thế, linh hoạt; chọn đúng người để theo thì hanh thông.',
    image: 'Đầm chứa sấm — quân tử lúc tối thì vào nghỉ, thuận tự nhiên.', tone: 'cát' },
  '蛊': { num: 18, nameVi: 'Cổ', nature: 'hư hỏng, sửa chữa',
    fortune: 'Núi trên gió — gió dưới núi, cái đỉnh hư. Cơ nghiệp tổ tiên suy bại cần sửa; dũng cảm đối mặt, «tiên giáp hậu giáp» mỗi 3 ngày.',
    image: 'Gió dưới núi — quân tử chấn động dân, nuôi dưỡng đức.', tone: 'trung' },
  '临': { num: 19, nameVi: 'Lâm', nature: 'tiến lên, giám sát',
    fortune: 'Đất tiến bao đầm — tiến lên lớn mạnh. «chí bát nguyệt hữu hung» — thịnh cực tất suy, tận dụng thời tốt để phòng tương lai.',
    image: 'Đất tiến đầm — quân tử giáo dục vô cùng, tư tưởng mãi.', tone: 'cát' },
  '观': { num: 20, nameVi: 'Quán', nature: 'quan sát, chiêm ngưỡng',
    fortune: 'Gió trên đất — gió khắp đất, quan sát mọi nơi. Trên làm gương cho dưới, ngắm nhìn suy tư sâu; không vội hành động.',
    image: 'Gió đất — vua đi tuần, quan dân thiết giáo.', tone: 'trung' },
  '噬嗑': { num: 21, nameVi: 'Thệ Hạp', nature: 'cắn qua, xử lý trở ngại',
    fortune: 'Lửa trên sấm — vật mắc giữa «phụ» cần cắn qua để thông. Hình phạt minh bạch xử lý trở ngại, dùng mạnh nhưng chính trực.',
    image: 'Sấm chớp — vua minh phạt, áp dụng luật rõ ràng.', tone: 'trung' },
  '贲': { num: 22, nameVi: 'Bí', nature: 'trang sức, vẻ đẹp',
    fortune: 'Núi trên lửa — lửa chiếu núi, vẻ đẹp trang sức. Chú trọng hình thức thẩm mỹ; nhưng «bạch bí» (trắng đơn giản) mới là đỉnh, đừng quá phù phiếm.',
    image: 'Lửa dưới núi — quan phủ minh chánh trị dân.', tone: 'cát' },
  '剥': { num: 23, nameVi: 'Bác', nature: 'bị tước đoạt, suy thoái',
    fortune: 'Núi trên đất — núi sụp đất, bóc lột. Âm thịnh dương suy, tiểu nhân đắc thế; tránh hành động, giữ gốc «sĩ quả» đợi «bác cực tất phục».',
    image: 'Núi sụp đất — kẻ trên dày, kẻ dưới yên ổn.', tone: 'hung' },
  '复': { num: 24, nameVi: 'Phục', nature: 'trở lại, hồi phục',
    fortune: 'Đất trên sấm — sấm dưới đất, dương khí hồi sinh. Sau cùng cực thì phục hồi, cơ hội thứ hai; nhân lúc phục mà tiến theo đạo.',
    image: 'Sấm trong đất — vua ngày chí bế quan, không đi lại.', tone: 'cát' },
  '无妄': { num: 25, nameVi: 'Vô Vọng', nature: 'không vọng động',
    fortune: 'Trời trên sấm — sấm dưới trời, động thuận thiên lý. Hành động thuận tự nhiên, chân thành thì cát; cố chấp phi đạo thì «vô vọng chi tai».',
    image: 'Trời sấm — vua thuận thời nuôi vạn vật phong phú.', tone: 'cát' },
  '大畜': { num: 26, nameVi: 'Đại Súc', nature: 'tích lũy lớn',
    fortune: 'Núi trên trời — núi chứa trời, tích lũy lớn. Tích tài năng đức độ tri thức, sẵn sàng phụng sự; «thiên chi đạo» đợi thời hành động lớn.',
    image: 'Trời trong núi — quân tử đa thức, học lời tiền nhân tu đức.', tone: 'cát' },
  '颐': { num: 27, nameVi: 'Di', nature: 'nuôi dưỡng',
    fortune: 'Núi trên sấm — hình miệng nhai, nuôi dưỡng. Chăm sóc bản thân + người; ăn nói cẩn thận, tiết độ sinh hoạt, nuôi đức.',
    image: 'Sấm núi — quân tử thận ngôn ngữ, tiết ẩm thực.', tone: 'trung' },
  '大过': { num: 28, nameVi: 'Đại Quá', nature: 'vượt quá mức',
    fortune: 'Đầm trên gió — «đống lũng» (dà cột cong), gánh quá nặng. Cảnh giới nguy, chỉ người kiệt xuất bản lĩnh phi thường mới vượt; bình thường thì khó.',
    image: 'Nước dìm cây — quân tử độc lập không sợ, nghiêm nghị.', tone: 'hung' },
  '坎': { num: 29, nameVi: 'Khảm', nature: 'hiểm trở trùng',
    fortune: 'Nước trên nước — hiểm trên hiểm, thử thách chồng chất. Giữ lòng thành «duy tâm hanh», lần theo dấu vết thoát hiểm; đừng liều lĩnh.',
    image: 'Nước chảy liên — quân tử hằng đức, hành động kiên trì.', tone: 'hung' },
  '离': { num: 30, nameVi: 'Ly', nature: 'sáng, phụ thuộc',
    fortune: 'Lửa trên lửa — sáng nối sáng, tài năng rực rỡ. Cần vật nuôi (phụ), giữ đạo thì sáng lâu; «hào đột» bốc cháy hung, cẩn thận.',
    image: 'Sáng đôi — đại nhân nối sáng chiếu四方 phương.', tone: 'cát' },
  '咸': { num: 31, nameVi: 'Hàm', nature: 'cảm ứng',
    fortune: 'Đầm trên núi — đầm nữ núi nam, giao cảm. Cảm ứng lẫn nhau, tình cảm tự nhiên vô tư; hôn nhân tốt, cần chừng mực chính đạo.',
    image: 'Núi trên đầm — quân tử hư tâm tiếp người, bao dung.', tone: 'cát' },
  '恒': { num: 32, nameVi: 'Hằng', nature: 'bền vững lâu dài',
    fortune: 'Sấm trên gió — sấm gió lâu dài, bền. Tính ôn hoà điềm đạm, thích ổn định; tình duyên bền nhưng dễ nhàm chán, cần «lập bất dịch phương».',
    image: 'Sấm gió — quân tử lập không đổi phương hướng.', tone: 'cát' },
  '遁': { num: 33, nameVi: 'Độn', nature: 'lùi lại, ẩn tránh',
    fortune: 'Trời trên núi — núi dưới trời, lùi. Tiểu nhân đắc thế, quân tử lùi đúng lúc; tránh xa kẻ xấu, bảo toàn lực, đợi thời «hảo độn».',
    image: 'Trời dưới núi — quân tử xa tiểu nhân, không ghét mà lùi.', tone: 'trung' },
  '大壮': { num: 34, nameVi: 'Đại Tráng', nature: 'mạnh mẽ',
    fortune: 'Sấm trên trời — sức mạnh dồi dào, uy lực. Dám đột phá, lãnh đạo bẩm sinh; nhưng dễ kiêu ngạo, dùng lễ chế cường «phi lễ phất lý».',
    image: 'Sấm trên trời — quân tử phi lễ không hành động.', tone: 'cát' },
  '晋': { num: 35, nameVi: 'Tấn', nature: 'thăng tiến',
    fortune: 'Lửa trên đất — mặt trời mọc lên đất, tiến. Như nhật thăng, được trên tin dùng; tận dụng minh đức tiến, hào phóng ban ân.',
    image: 'Sáng ra đất — quân tử tự chiếu minh đức.', tone: 'cát' },
  '明夷': { num: 36, nameVi: 'Minh Di', nature: 'sáng bị tổn',
    fortune: 'Đất trên lửa — lửa chìm đất, sáng bị che. Người tài gặp thời loạn, ẩn mình «lý kỳ dực»; ngoại thuận nội kiên, đợi sáng trở lại.',
    image: 'Sáng vào đất — quân tử dùng hám quần, lùi tránh.', tone: 'hung' },
  '家人': { num: 37, nameVi: 'Gia Nhân', nature: 'gia đình, trật tự',
    fortune: 'Gió trên lửa — lửa gió trong nhà. Trong nhà có đạo, chồng ngoài vợ trong; quản gia tốt rồi mới ra ngoài lập nghiệp.',
    image: 'Gió từ lửa — quân tử nói có thực, giữ uy.', tone: 'cát' },
  '睽': { num: 38, nameVi: 'Khuê', nature: 'trái ngược, chia lìa',
    fortune: 'Lửa trên đầm — lửa bốc đầm chìm, trái ngược. Hai bên khác ý khó hoà; tìm điểm chung trong khác biệt «đồng nhi dị».',
    image: 'Lửa đầm trái nhau — quân tử đồng mà dị, cầu đồng tồn dị.', tone: 'trung' },
  '蹇': { num: 39, nameVi: 'Kiển', nature: 'khó nhọc, vấp váp',
    fortune: 'Nước trên núi — nước núi hiểm trở. Khó nhọc trước mặt; không tiến thì lui, tìm người đạo đức giúp, tu đức «phản tu thân» để qua nạn.',
    image: 'Núi nước — quân tử phản tỉnh tu thân.', tone: 'hung' },
  '解': { num: 40, nameVi: 'Giải', nature: 'tháo gỡ, giải quyết',
    fortune: 'Sấm trên nước — sấm mưa, giải toả bế tắc. Giỏi giải quyết vấn đề; nhường lại cho người, đừng dùng vũ lực, tránh dễ dãi.',
    image: 'Sấm mưa — quân tử tha quá, khoan thứ tội lỗi.', tone: 'cát' },
  '损': { num: 41, nameVi: 'Tổn', nature: 'giảm bớt',
    fortune: 'Núi trên đầm — giảm dưới bồi trên, hy sinh nhỏ nuôi đức lớn. Giữ lòng thành «hữu phù», tổn cực thành ích; đừng tổn quá mức.',
    image: 'Núi đầm — quân tử trừng phẫn, trệ dục (ngăn giận, dập dục).', tone: 'trung' },
  '益': { num: 42, nameVi: 'Ích', nature: 'lợi ích, tăng trưởng',
    fortune: 'Gió trên sấm — sấm gió, tăng trưởng. Mang lại giá trị cho người, hợp tác tốt; «thiết lợi» cho dân, lúc tốt thì tiến mạnh.',
    image: 'Gió sấm — quân tử thấy thiện thì tiến, có lỗi thì đổi.', tone: 'cát' },
  '夬': { num: 43, nameVi: 'Quái', nature: 'quyết đoán, loại trừ',
    fortune: 'Đầm trên trời — một âm còn lại trên 5 dương, quyết đoán. Dũng cảm loại tiểu nhân; nhưng cẩn trọng, dùng đức đừng dùng bạo «bất lợi tức nhung».',
    image: 'Đầm trời — quân tử ban lộc đến dưới, dùng ân.', tone: 'trung' },
  '姤': { num: 44, nameVi: 'Cấu', nature: 'gặp gỡ, cơ duyên',
    fortune: 'Trời trên gió — một âm bắt đầu xâm nhập, gặp gỡ. Cẩn thận duyên tình ngẫu nhiên «nhất âm sinh», đừng để tiểu nhân xâm nhập.',
    image: 'Trời gió — vua thi mệnh cáo bốn phương.', tone: 'trung' },
  '萃': { num: 45, nameVi: 'Tụy', nature: 'tụ tập, hội tụ',
    fortune: 'Đầm trên đất — nước tụ đất, hội tụ. Vạn vật tụ hội, cần chính đạo; tìm người tài, dùng vũ khí phòng bị, tế lễ đoàn kết.',
    image: 'Đầm đất — quân tử sửa vũ khí phòng bất trắc.', tone: 'cát' },
  '升': { num: 46, nameVi: 'Thăng', nature: 'thăng tiến, lên cao',
    fortune: 'Đất trên gió — cây mọc trong đất, lên. Từ dưới tiến lên trên thuận tự nhiên «nhược mộc»; nhỏ mà lớn dần, không nôn nóng.',
    image: 'Đất sinh cây — quân tử thuận đức, tích nhỏ thành cao.', tone: 'cát' },
  '困': { num: 47, nameVi: 'Khốn', nature: 'khốn đốn, kìm hãm',
    fortune: 'Đầm trên nước — đầm không nước, khốn. Người tài bị kìm «hữu ngôn bất tín», lời không ai tin; giữ lạc quan tu đức, nói có tin, hành có kết.',
    image: 'Đầm không nước — quân tử trí mạng toả chí (liều mạng toả chí).', tone: 'hung' },
  '井': { num: 48, nameVi: 'Tỉnh', nature: 'nuôi dưỡng, bất biến',
    fortune: 'Nước trên gió — giếng nuôi dưỡng muôn người không đổi «cải 邑 bất cải tỉnh». Cải tạo hoàn cảnh, giữ gốc, tận tâm phụng sự.',
    image: 'Gỗ nước — quân tử khuyến dân giúp nhau.', tone: 'trung' },
  '革': { num: 49, nameVi: 'Cách', nature: 'cách mạng, đổi mới',
    fortune: 'Đầm trên lửa — «nhị nữ đồng cư» xung đột, cách. Thay đổi thời đại lật đổ cũ; cần đức tín, đúng thời «kỷ nhật nãi phù», dân tin mới làm.',
    image: 'Đầm lửa — quân tử trị lịch, minh rõ thời tiết.', tone: 'trung' },
  '鼎': { num: 50, nameVi: 'Đỉnh', nature: 'đỉnh, biến đổi tốt',
    fortune: 'Lửa trên gió — gió lửa đỉnh, nấu tế. Vị thế cao ổn định «đỉnh», nhận trọng trách; giữ đức «kim hoàng», biến đổi tốt đẹp, yên định.',
    image: 'Lửa trên gỗ — quân tử chính vị, ngưng mệnh.', tone: 'cát' },
  '震': { num: 51, nameVi: 'Chấn', nature: 'sấm, bùng nổ',
    fortune: 'Sấm trên sấm — sấm động liên, sợ mà tu đức. Uy lực bẩm sinh bùng nổ; «tiếu ngôn ác ác» sau sợ, giữ tâm bình tĩnh «chấn lai đê đê».',
    image: 'Sấm đôi — quân tử khủng cụ tu tỉnh (sợ mà tỉnh ngộ).', tone: 'trung' },
  '艮': { num: 52, nameVi: 'Cấn', nature: 'dừng lại, tĩnh',
    fortune: 'Núi trên núi — núi nặng, dừng đúng chỗ «cấn kỳ bối». Dừng đúng lúc đúng chỗ, chú trọng nội tâm, tĩnh lặng tu dưỡng.',
    image: 'Đôi núi — quân tử nghĩ không ra ngoài vị trí mình.', tone: 'trung' },
  '渐': { num: 53, nameVi: 'Tiệm', nature: 'tiến từ từ',
    fortune: 'Gió trên núi — cây trên núi, tiến chậm. Như nhạn bay dần lên «hồng tiệm», đúng quy trình, không nôn nóng; hôn nhân theo lễ bền.',
    image: 'Núi cây — quân tử cư hiền đức, thiện hoá phong tục.', tone: 'cát' },
  '归妹': { num: 54, nameVi: 'Quy Muội', nature: 'duyên muộn, trật tự',
    fortune: 'Sấm trên đầm — «đệ muội» gả «vô quân», vị trái. Duyên tình trắc trở đầu đời, cuối bình yên «nữ chi chung dã»; kiên nhẫn, duyên muộn bền.',
    image: 'Đầm sấm — quân tử vĩnh chung, biết rõ tệ đoan.', tone: 'hung' },
  '丰': { num: 55, nameVi: 'Phong', nature: 'phong phú, thịnh',
    fortune: 'Sấm trên lửa — sấm chớp «thịnh». Tài đa phong phú, đỉnh cao «nghi nhật trung»; nhưng «nhật trung tắc nghệt», thịnh tất suy nên cẩn.',
    image: 'Sấm chớp — quân tử chiết ngục, xét kiện hình sự.', tone: 'cát' },
  '旅': { num: 56, nameVi: 'Lữ', nature: 'du hành, phiêu bạt',
    fortune: 'Lửa trên núi — lửa cháy qua núi, tạm. Du hành tạm trú, xa nhà lập nghiệp «lữ tức thứ»; cẩn giữ mình, linh hoạt, nhanh nhẹn.',
    image: 'Núi lửa — quân tử minh hình, xét kiện thận trọng.', tone: 'trung' },
  '巽': { num: 57, nameVi: 'Tốn', nature: 'thuận theo, thấm',
    fortune: 'Gió trên gió — gió nối gió, thấm mọi nơi «trọng vũ». Mềm mại thuận theo, lệnh trên truyền dưới; khiêm nhường kiên nhẫn thuyết phục.',
    image: 'Gió theo gió — quân tử thân mệnh hành sự (lệnh trên truyền dưới).', tone: 'trung' },
  '兑': { num: 58, nameVi: 'Đoài', nature: 'vui vẻ, giao tiếp',
    fortune: 'Đầm trên đầm — vui vẻ «hoà hoãn», giao tiếp thu phục lòng người. Nhưng vui quá «lai huỳnh» dễ đắm chìm, cần chính đạo «hoà hoãn cát」.',
    image: 'Đôi đầm — quân tử bạn hữu giảng tập, học hỏi bạn bè.', tone: 'cát' },
  '涣': { num: 59, nameVi: 'Hoán', nature: 'phân tán, giải toả',
    fortune: 'Gió trên nước — gió tan nước «tán». Gió tan mây giải toả bế tắc «hoán hanh»; phân tán để quy tụ lại, dùng chân thành «vương cách hữu miếu».',
    image: 'Gió nước — vua cúng tế Thượng Đế, lập miếu.', tone: 'trung' },
  '节': { num: 60, nameVi: 'Tiết', nature: 'giới hạn, tiết độ',
    fortune: 'Nước trên đầm — nước trong đầm có giới, tiết độ «cát tiết hanh». Tiết chế có chừng; quá «khổ tiết» khổ, không tiết thì loạn.',
    image: 'Đầm nước — quân tử chế sổ độ, nghị đức hành (định số độ, bàn đức hành).', tone: 'trung' },
  '中孚': { num: 61, nameVi: 'Trung Tín', nature: 'lòng thành',
    fortune: 'Gió trên đầm — «trung phu», lòng thành bên trong. Cảm hoá người «đồn ngư cát», tin tưởng lẫn nhau; lập thân «tín cập thì ngư».',
    image: 'Đầm gió — quân tử nghị ngục hoãn tử (xét kiện khoan thứ).', tone: 'cát' },
  '小过': { num: 62, nameVi: 'Tiểu Quá', nature: 'vượt nhỏ',
    fortune: 'Sấm trên núi — «phi điểu» chim bay quá «phi điểu di chi hung». Việc nhỏ thì tốt «khả tiểu sự», việc lớn dè chừng «bất khả đại sự»; khiêm cung «cung kiêm».',
    image: 'Núi sấm — quân tử hành quá cung (làm quá mức phải cung kính).', tone: 'trung' },
  '既济': { num: 63, nameVi: 'Ký Tế', nature: 'đã hoàn thành',
    fortune: 'Nước trên lửa — «kỷ tế» hoàn thành trật tự ổn định «sơ cát». Nhưng «chư loạn» — thịnh cực sinh loạn, dự phòng tương lai «tư nhi dự lập」.',
    image: 'Nước lửa — quân tử tư hoạn, dự phòng trước.', tone: 'cát' },
  '未济': { num: 64, nameVi: 'Vị Tế', nature: 'chưa hoàn thành',
    fortune: 'Lửa trên nước — «vị tế» chưa xong tiềm năng lớn «vị tế hanh». Hy vọng phía trước, nỗ lực không ngừng; đợi lúc chuyển sang Ký Tế.',
    image: 'Lửa nước — quân tử thận biện vật cư phương (thận trọng phân biệt vật, đặt đúng chỗ).', tone: 'trung' },
};

// Map giản → phồn (heluo dùng giản; guiguzi-fdg dùng phồn). Lookup hỗ trợ cả 2.
const SIMP2TRAD = {
  '离': '離', '坎': '坎', '师': '師', '复': '復', '节': '節', '观': '觀', '临': '臨',
  '归妹': '歸妹', '无妄': '無妄', '丰': '豐', '渐': '漸', '蛊': '蠱', '贲': '賁',
  '剥': '剝', '损': '損', '兑': '兌', '涣': '渙', '晋': '晉', '蹇': '蹇', '未济': '未濟',
  '既济': '既濟', '随': '隨', '革': '革', '鼎': '鼎', '升': '升', '萃': '萃', '困': '困',
  '井': '井', '小过': '小過', '大过': '大過', '中孚': '中孚', '家人': '家人', '讼': '訟',
  '需': '需', '比': '比', '泰': '泰', '否': '否', '谦': '謙', '豫': '豫', '小畜': '小畜',
  '大畜': '大畜', '大壮': '大壯', '恒': '恆', '咸': '咸', '益': '益', '噬嗑': '噬嗑',
  // [loop 577 FIX] 3 entry thiếu: 颐→頤 (Di#27), 遁→遯 (Độn#33). 恒→恆 (sửa từ '恒' sai).
  '颐': '頤', '遁': '遯',
  '旅': '旅', '屯': '屯', '蒙': '蒙', '震': '震', '艮': '艮', '巽': '巽', '乾': '乾',
  '坤': '坤', '夬': '夬', '姤': '姤', '同人': '同人', '大有': '大有',
};

export function hexagramMeaning(name) {
  if (!name) return null;
  const e = HEX_MEANING[name] || HEX_MEANING[SIMP2TRAD[name]];
  if (e) return e;
  // thử ngược: nếu name là phồn, tìm giản tương ứng
  const simp = Object.keys(SIMP2TRAD).find((k) => SIMP2TRAD[k] === name);
  if (simp && HEX_MEANING[simp]) return HEX_MEANING[simp];
  return { nameVi: name, nature: '', fortune: '(chưa cài nghĩa VN cho quẻ này)', image: '', tone: 'trung' };
}

// [loop 1208] 大象传 (周易) — 5 quẻ nền tảng, verse Hán gốc (HEX_MEANING.image là paraphrase Việt).
//   Nguồn: Wikisource 周易/大象 + 清华大学课程 + 识典古籍.
export const DAXIANG = {
  乾: { verse: '天行健，君子以自强不息。', apply: 'thiên đạo cương kiện vận hành không ngừng — quân tử tự cường không nghỉ.' },
  坤: { verse: '地势坤，君子以厚德载物。', apply: 'địa thế nhu thuận — quân tử lấy hậu đức tải vạn vật.' },
  屯: { verse: '云雷，屯；君子以经纶。', apply: 'vân lôi giao động, sơ sáng gian nan — quân tử kinh luận thiên hạ.' },
  蒙: { verse: '山下出泉，蒙；君子以果行育德。', apply: 'núi dưới suối trào, mông muội sơ khai — quân tử quả quyết hành, dục đức.' },
  既济: { verse: '水在火上，既济；君子以思患而预防之。', apply: 'thuỷ trên hoả, việc đã thành — quân tử tư hoạn mà dự phòng.' },
};

export { HEX_MEANING, SIMP2TRAD };
